### ISSUE TITLE
is this w3c compatible today ?

### ISSUE THREAD

**Issue by lucasverra** [GoogleChromeLabs/perception-toolkit#107]
hi there, one mobile PWA of my startup ecosystem use a fairly known open source JS library to scan QR codes in reactJS & redux application. 
Our (scanner) PWA works on most devices because w3c compatible. 

is this perception kit ready to be used in production because it’s compatible with ios > 11 and android > last 3 years ? 

 I am very interested in replacing libraries if it’s compatible with most devices on market (EU) right now. I really think that this can be a game changer in terms of user experience

**Comment by mmocny** [comment]
Hello Lucas!  Thanks for asking.

This toolkit attempts to use an upcoming proposal from The Web Platform Incubator Community Group (WICG) group, called [Shape Detection API](https://wicg.github.io/shape-detection-api/), and specifically its [Barcode Detection API](https://wicg.github.io/shape-detection-api/#barcode-detection-api).  ([Learn more here](https://developers.google.com/web/updates/2019/01/shape-detection)).

However, as per the current spec status:

> This specification was published by the Web Platform Incubator Community Group. It is not a W3C Standard nor is it on the W3C Standards Track.

...So this is still a very early and aspirational proposal, not widely available as a browser feature.  To work around this, we use a WASM module for barcode detection, which does work well on iOS and Android devices.

Our toolkit is very new, so we have not had the ability to test on a broad range of devices, yet -- though we do test older iPhone, Pixel 1, and certain Samsung devices.  I would suggest that if you only want raw barcode scanning, and your current library is working well for you, that this may not be a safe replacement.

The Web Perception Toolkit is using barcode scanning (and image detection) provided by other libraries.  Our primary goal is to link these real world targets to web content, mapped easily with simple Structured Data annotations, and with UI that works out of the box for most cases.

Thanks for your interest, please dl try it out and ask questions here!
