### ISSUE TITLE
Meaning Maker tests are flaky due to rotating karma serving port number

### ISSUE THREAD

**Issue by mmocny** [GoogleChromeLabs/perception-toolkit#135]
Several MM tests rely on a fixed port number for karma tests (in order to test dynamic discovery via target URL).

Because the URL has to match exactly what is specified in the structured data, and because the structured data is currently hardcoded to a specific portNum (9876), but I'm sometimes getting karma served on other ports (e.g. 9877).

Ideally the test assets would be templated and supplied to domain:portNum value.  However, could workaround the issue by implementing support for relative URLs, which we want anyway (#97).

I will disable these tests for now to stop the flake.

**Comment by paullewis** [comment]
sg. I think we want to go with #97 rather than making the test suite any more complicated.

**Comment by mmocny** [comment]
#136 already fixes the tests in a way that isn't complicated at all.  It also improves the tests in the process.
