### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by renambot-uic** [GoogleChromeLabs/perception-toolkit#137]
After 'git clone', running 'npm install' fails:

src/artifacts/artifact-loader.ts:73:25 - error TS2304: Cannot find name 'NodeSelector'.
73   async fromElement(el: NodeSelector, url: URL|string): Promise<ARArtifact[]> {

Tried on Mac and Linux, Node 11 and 12.

**Comment by mmocny** [comment]
Very interesting. This code hasn't changed in a while but I noticed this
was highlighted as a warning today. Wonder if typescript changed the
interfaces for Dom API and I used the wrong types.  I'm really only trying
to state the need for query selector API so I may just do that directly.

I already changed that code you reference in another PR.

May I ask you to test again tomorrow?

**Comment by renambot-uic** [comment]
> May I ask you to test again tomorrow?

Sure, no problem

**Comment by paullewis** [comment]
FWIW I'm unable to repro off master right now using TypeScript 3.5.2, Node 11.9 on Mac. Curious.

**Comment by renambot-uic** [comment]
It installs now, with the latest commits.
thanks.

**Comment by mmocny** [comment]
Thank you!
