### ISSUE TITLE
Prepare the repo for public release

### ISSUE THREAD

**Issue by smalls** [GoogleChromeLabs/perception-toolkit#17]
Including:

- Licensing
- Guidelines for new contributors (creating PRs, creating issues)
- Release process
- Proposed roadmap

**Comment by smalls** [comment]
Rule requiring PRs for master: https://github.com/GoogleChromeLabs/perception-toolkit/settings/branch_protection_rules/5267716

I thought about enforcing a merge style (squash?) but maybe that's not really needed.

**Comment by mmocny** [comment]
I think we need to file separate issues for the specific parts of this which we still find critical.  We're unlikely to look at this Issue at this point and make it actionable.
