### ISSUE TITLE
Refactor the demo site

### ISSUE THREAD

**Issue by smalls** [GoogleChromeLabs/perception-toolkit#87]
New additions to the demo site:

* Split in-line json-ld into the detail pages, reference only the sitemap-ish json-ld from index.html
* Script for building the sitemap-ish json-ld from detail pages
* Include more detail pages (maybe 3?)
* Better commenting for all json-lds, so the use is a bit clearer
* A consolidated use case (Shop? Cities of the world? Art is available on unsplash.com)
* A few different demo card display types; although we're not sure if we need the card comparison

**Comment by mmocny** [comment]
At this point there are 3 broad themes left to work on:

1. Demo which showcases aftifact-map generation script. (depends on finishing that work)
2. Restructure Demo pages around a pretty use case (right now, its geeky and content-less)
3. Demo for more advanced card types (at least adding buttons and tracking state, e.g. comparison shopping?)

**Comment by mmocny** [comment]
Filed distinct issues #141 #142 #143
